apiVersion: v1
kind: Secret
metadata:
  name: backend-env
  namespace: itmovito
type: Opaque
stringData:
  DATABASE_URL: postgresql://user:password@db:5432/nestdb
  CORS_ORIGINS: http://localhost:8080,http://127.0.0.1:8080,http://171.22.74.190
