---
- name: Install Docker on VM
  hosts: vm
  become: true

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: true

    - name: Start and enable Docker
      service:
        name: docker
        state: started
        enabled: true

    - name: Add SSH user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true
